-- +migrate Up
CREATE TABLE targets (
     id INT AUTO_INCREMENT PRIMARY KEY,
     ip VARCHAR(255) NOT NULL UNIQUE COMMENT 'IP',
     name VARCHAR(255) NOT NULL DEFAULT '' COMMENT '企業名',
     status VARCHAR(50) NOT NULL DEFAULT 'init' COMMENT 'ステータス',
     update_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
     create_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='IP情報テーブル';

-- +migrate Down
DROP TABLE IF EXISTS targets;