-- +migrate Up
CREATE TABLE domains (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    can_view BOOLEAN NOT NULL DEFAULT false,
    is_send BOOLEAN NOT NULL DEFAULT false,
    title VARCHAR(255) NOT NULL DEFAULT '',
    owner_id VARCHAR(255) NOT NULL DEFAULT '',
    address VARCHAR(500) NOT NULL DEFAULT '',
    phone VARCHAR(50) NOT NULL DEFAULT '',
    industry VARCHAR(255) NOT NULL DEFAULT '',
    is_ssl BOOLEAN NOT NULL DEFAULT false,
    raw_page TEXT NOT NULL,
    page_num INT NOT NULL DEFAULT 0,
    status VARCHAR(50) NOT NULL DEFAULT 'initialize',
    update_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    create_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- +migrate Down
DROP TABLE IF EXISTS domains;