// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/domains": {
            "get": {
                "description": "Get domain list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ドメイン"
                ],
                "summary": "Get domains",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ドメイン名",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "閲覧可能か",
                        "name": "can_view",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "日本のサイトか",
                        "name": "is_japan",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "mapsで問い合わせページを開いたか",
                        "name": "is_send",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "owner_id",
                        "name": "owner_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ステータス",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "業種",
                        "name": "industry",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "SSL対応可否",
                        "name": "is_ssl",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.Domains"
                            }
                        }
                    }
                }
            }
        },
        "/domains/analyze": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ドメイン"
                ],
                "summary": "サイトの情報を解析する",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/domains/{id}": {
            "get": {
                "description": "Get domain",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ドメイン"
                ],
                "summary": "Get domain",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Domain"
                        }
                    }
                }
            },
            "put": {
                "description": "Update domain information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ドメイン"
                ],
                "summary": "Update domain",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新ドメイン情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateDomain"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Domain"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete domain by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ドメイン"
                ],
                "summary": "Delete domain",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/external/api/deploy": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wordpress"
                ],
                "summary": "ワードプレスをデプロイします",
                "parameters": [
                    {
                        "description": "デプロイ情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.DeployRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/fetch": {
            "post": {
                "description": "Fetch domain information from target",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ViewDNS"
                ],
                "summary": "Fetch domains",
                "parameters": [
                    {
                        "description": "Fetch request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PostFetchRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted"
                    }
                }
            }
        },
        "/logs": {
            "get": {
                "description": "Get log list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ログ"
                ],
                "summary": "Get logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "処理名",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "カテゴリー",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.Logs"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create new log",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ログ"
                ],
                "summary": "Create log",
                "parameters": [
                    {
                        "description": "作成ログ情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateLog"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.Log"
                        }
                    }
                }
            }
        },
        "/targets": {
            "get": {
                "description": "Get target list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ターゲット"
                ],
                "summary": "Get targets",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Target"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create new target",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ターゲット"
                ],
                "summary": "Create target",
                "parameters": [
                    {
                        "description": "作成ターゲット情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateTargetRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Target"
                        }
                    }
                }
            }
        },
        "/targets/{id}": {
            "put": {
                "description": "Update target information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ターゲット"
                ],
                "summary": "Update target",
                "parameters": [
                    {
                        "description": "更新ターゲット情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateTargetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Target"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete target by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ターゲット"
                ],
                "summary": "Delete target",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/tasks": {
            "get": {
                "description": "Get task list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "タスク"
                ],
                "summary": "Get tasks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Task"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create new task",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "タスク"
                ],
                "summary": "Create task",
                "parameters": [
                    {
                        "description": "作成タスク情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Task"
                        }
                    }
                }
            }
        },
        "/tasks/execute": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "タスク"
                ],
                "summary": "全てのタスクを実行します",
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/tasks/{id}": {
            "put": {
                "description": "Update task information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "タスク"
                ],
                "summary": "Update task",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新タスク情報",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Task"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete task by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "タスク"
                ],
                "summary": "Delete task",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/tasks/{id}/execute": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "タスク"
                ],
                "summary": "タスクを実行します",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.Deploy": {
            "type": "object",
            "properties": {
                "domain": {
                    "type": "string"
                },
                "server_id": {
                    "type": "string"
                }
            }
        },
        "model.CreateTargetRequest": {
            "type": "object",
            "properties": {
                "ip": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.CreateTaskRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "model.PostFetchRequest": {
            "type": "object",
            "required": [
                "target"
            ],
            "properties": {
                "target": {
                    "type": "string"
                }
            }
        },
        "model.Status": {
            "type": "string",
            "enum": [
                "unknown",
                "initialize",
                "check_view",
                "check_japan",
                "crawl_comp_info",
                "done",
                "trash"
            ],
            "x-enum-varnames": [
                "StatusUnknown",
                "StatusInitialize",
                "StatusCheckView",
                "StatusCheckJapan",
                "StatusCrawlCompInfo",
                "StatusDone",
                "StatusTrash"
            ]
        },
        "model.Target": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ip": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/model.TargetStatus"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.TargetStatus": {
            "type": "string",
            "enum": [
                "init",
                "fetched"
            ],
            "x-enum-varnames": [
                "TargetStatusInit",
                "TargetStatusFetched"
            ]
        },
        "model.Task": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.UpdateTargetRequest": {
            "type": "object",
            "properties": {
                "ip": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.UpdateTaskRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "request.CreateLog": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "request.DeployRequest": {
            "type": "object",
            "properties": {
                "dst": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Deploy"
                    }
                },
                "src": {
                    "$ref": "#/definitions/entity.Deploy"
                }
            }
        },
        "request.UpdateDomain": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "can_view": {
                    "type": "boolean"
                },
                "company": {
                    "type": "string"
                },
                "industry": {
                    "type": "string"
                },
                "is_japan": {
                    "type": "boolean"
                },
                "is_send": {
                    "type": "boolean"
                },
                "is_ssl": {
                    "type": "boolean"
                },
                "landline_phone": {
                    "type": "string"
                },
                "mobile_phone": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                },
                "page_num": {
                    "type": "integer"
                },
                "phone": {
                    "type": "string"
                },
                "prefecture": {
                    "type": "string"
                },
                "president": {
                    "type": "string"
                },
                "raw_page": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/model.Status"
                },
                "target": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "response.Domain": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "can_view": {
                    "type": "boolean"
                },
                "company": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "industry": {
                    "type": "string"
                },
                "is_japan": {
                    "type": "boolean"
                },
                "is_send": {
                    "type": "boolean"
                },
                "is_ssl": {
                    "type": "boolean"
                },
                "landline_phone": {
                    "type": "string"
                },
                "mobile_phone": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                },
                "page_num": {
                    "type": "integer"
                },
                "phone": {
                    "type": "string"
                },
                "prefecture": {
                    "type": "string"
                },
                "president": {
                    "type": "string"
                },
                "raw_page": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/model.Status"
                },
                "target": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "response.Domains": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "domains": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.Domain"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.Log": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "response.Logs": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "logs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.Log"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Sales API",
	Description:      "Type \"Bearer\" followed by a space and JWT token.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
