name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Go"]
    types:
      - completed
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: deploy
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /var/www/sales
            git fetch --all
            git reset --hard origin/main
            sudo systemctl daemon-reload
            sudo systemctl restart sales-api